pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    node_10_x:
      node_version: 10.x

trigger:
  tags:
    include: ['*']

variables:
- group: NPM Variables
steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)

- script: |
    echo '//registry.npmjs.org/:_authToken=$(NPM_TOKEN)' > .npmrc
    npm install 
    npm run build
    npm publish
  displayName: 'deploy'
