pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    node_10_x:
      node_version: 10.x

trigger:
  branches:
    include:
      - refs/heads/master
  tags:
    include:
      - refs/tags/v*

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)

- script: |
    echo "//registry.npmjs.org/:_authToken=$(NPM_TOKEN)" > .npmrc
    npm install 
    npm build
    npm publish
  displayName: 'deploy'
